short_name = "godot"
name = "Godot Engine"
major = 4
minor = 4
patch = 1
custom_patch = 1
custom_name = "Green Crow Games"
status = "dev"
module_config = ""
website = "https://godotengine.org"
docs = "4.4"
